#!/bin/sh

Usage() {
  cat <<EOF
    ___________ _   ____
   / ____|__  // | / / /
  / /     /_ </  |/ / /
 / /___ ___/ / /|  / /___
 \____//____/_/ |_/_____/

Niall J. Bourke Imperial College London March 2020
n.bourke@imperial.ac.uk
Original script by Martin M Monti (monti@psych.ucla.edu)

##
usage:  make_sphere_roi <input_image.nii.gz> <x y z> <mm>
e.g. make_sphere_roi MNI152_T1_1mm.nii.gz 45 71 58 5
##

<input image> is an image that has the same resolution as the image you want to apply the ROI to.
NOTE: this image either has to be in the folder you are launching the command from, or has to have a full path.

<x y z> are the ROI coordinates
NOTE: These are voxel coordinates that can be acquired from fsleyes, based on MNI coordinates from a paper (or better average of multiple sources)

<mm>  is the width of the ROI.

Output is defaulted to current working directory

EOF

  exit 1
}

# if less than two arguments supplied, display usage
	if [  $# -le 4 ]
	then
		Usage
		exit 1
	fi

# check whether user had supplied -h or --help . If yes display usage
	if [[ ( $# == "--help") ||  $# == "-h" ]]
	then
		Usage
		exit 0
	fi

module load fsl

echo "******************************"
echo "Input image: ${1} "
echo "ROI coordinates: ${2} ${3} ${4} "
echo "ROI size: ${5} "
p=`pwd` #${EPHEMERAL}
fslmaths ${1} -roi $2 1 $3 1 $4 1 0 1 ${p}/tmp_point_mask
fslmaths ${p}/tmp_point_mask -kernel sphere $5 -fmean -bin ${p}/mask_sphere_${2}-${3}-${4} -odt float
rm ${p}/tmp_point_mask.*
echo "Done! The output file is called 'mask_sphere_${2}-${3}-${4}_${5}mm' "
echo " "
